### ISSUE TITLE
Duplicate id value for 20! Again... Using latest version

### ISSUE THREAD

**Issue by Solar-Tiger** [Wehavecookies56/Kingdom-Keys-1.7-8#21]
http://pastebin.com/4uKi0wF4

That's the crash log, so I don't know what's wrong but it redirects to your mod... Something along the line of ID's not related to Enchanting of any sort that I'm aware of...

Solar_Tiger

**Comment by Abelatox** [comment]
Right now the mod may be incompatible with other mods, even battlegear. We look forward to make another method to not override slots.
(That's not an enchantment issue)
